json.id product.id 
json.name product.name 
json.price product.price 
json.is_discounted? product.is_discounted? 
json.tax product.tax 
json.total product.total 
json.description product.description
json.supplier product.supplier  
json.images product.images 
json.updated_at product.updated_at 
json.created_at product.created_at